services:
  - type: web
    name: vilequiz
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_Model
        value: llama-3.3-70b-versatile
      - key: GROQ_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: vilequiz-redis
          property: connectionString

  - type: redis
    name: vilequiz-redis
    plan: free
    ipAllowList: [] # only allow internal connections
